Data Cleaning Tasks:

1.Deleting redundant columns.
2.Renaming the columns.
3.Dropping duplicates.
4.Cleaning individual columns.
5.Remove the NaN values from the dataset
6.Check for some more Transformations

In [239]:
import pandas as pd

In [240]:
pd.__version__

'2.3.3'

In [241]:
# Reading the csv file
data = pd.read_csv("zomato.csv")

In [242]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [243]:
data.tail()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [244]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [245]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [246]:
data.shape # to know the number of columns and rows

(51717, 17)

# 1.Deleting redundant columns

In [247]:
'''Redundant columns are columns that don't add new information 
because the same information already exists in other columns.'''

"Redundant columns are columns that don't add new information \nbecause the same information already exists in other columns."

In [248]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [249]:
columns_to_keep=['name', 'online_order', 'book_table', 'rate','dish_liked','approx_cost(for two people)']
columns_to_drop=['url', 'address','votes','phone', 'location', 'rest_type','cuisines','reviews_list', 'menu_item','listed_in(type)', 'listed_in(city)']

In [250]:
data.shape

(51717, 17)

In [251]:
len(columns_to_keep)

6

In [252]:
len(columns_to_drop)

11

## 1st Way - Filtering Data

In [253]:
type(data[["name","url"]])

pandas.core.frame.DataFrame

In [254]:
type(data["name"])

pandas.core.series.Series

In [255]:
# data["name","url"]
#  it cause an error 
# It causes an error because pandas expects a list of column names, not a tuple.

In [256]:
columns_to_keep

['name',
 'online_order',
 'book_table',
 'rate',
 'dish_liked',
 'approx_cost(for two people)']

In [257]:
modify_data = data[columns_to_keep]

In [258]:
modify_data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

## 2nd Way - Dropping the columns

In [259]:
columns_to_drop

['url',
 'address',
 'votes',
 'phone',
 'location',
 'rest_type',
 'cuisines',
 'reviews_list',
 'menu_item',
 'listed_in(type)',
 'listed_in(city)']

In [260]:
data.drop(columns=columns_to_drop,inplace=True)

In [261]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

# 2.Renaming the Columns

In [262]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [263]:
data.rename(columns={'name':'Name',},inplace=True) # changing one by one

In [264]:
data

,Name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [265]:
data.columns[0].capitalize()

'Name'

In [266]:
# changing all at once
for i in data.columns:
    print(i.capitalize())

Name
Online_order
Book_table
Rate
Dish_liked
Approx_cost(for two people)

In [267]:
new_col_names=[]
for i in data.columns:
    new_col_names.append(i.capitalize())

In [268]:
new_col_names

['Name',
 'Online_order',
 'Book_table',
 'Rate',
 'Dish_liked',
 'Approx_cost(for two people)']

In [269]:
data.columns = new_col_names

In [270]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [271]:
data.columns

Index(['Name', 'Online_order', 'Book_table', 'Rate', 'Dish_liked',
       'Approx_cost(for two people)'],
      dtype='object')

# 3. Dropping Duplicates

In [272]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51712     True
51713     True
51714    False
51715     True
51716     True
Length: 51717, dtype: bool

In [273]:
data.duplicated().sum()

np.int64(32808)

In [274]:
data.duplicated().value_counts()

True     32808
False    18909
Name: count, dtype: int64

In [275]:
data.drop_duplicates(inplace=True)

In [276]:
# data.duplicated().value_counts()
data.duplicated().sum()
# check still duplicate values are there or not

np.int64(0)

# Remove the NaN values from the dataset

In [277]:
data.isna().sum()

Name                               0
Online_order                       0
Book_table                         0
Rate                            2418
Dish_liked                     10587
Approx_cost(for two people)      140
dtype: int64

In [278]:
data.dropna(inplace=True)

In [279]:
data.isna().sum()

Name                           0
Online_order                   0
Book_table                     0
Rate                           0
Dish_liked                     0
Approx_cost(for two people)    0
dtype: int64

In [280]:
data.reset_index(inplace=True)

In [281]:
data.drop(columns='index',inplace=True)

In [282]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

# 4. Cleaning individual columns

In [283]:
type(data["Rate"][14])

str

In [284]:
data['Rate']

0        4.1/5
1        4.1/5
2        3.8/5
3        3.7/5
4        3.8/5
         ...
8245    2.5 /5
8246    3.6 /5
8247    3.8 /5
8248    4.2 /5
8249    2.5 /5
Name: Rate, Length: 8250, dtype: object

In [285]:
data["Rate"] = data["Rate"].str.replace(" ","")

In [286]:
data["Rate"] = data["Rate"].str.replace("/"," Out of ")

In [287]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1 Out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1 Out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8 Out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7 Out of 5,Masala Dosa,300
4,Grand Village,No,No,3.8 Out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 Out of 5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 Out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 Out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 Out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 Out of 5,"Biryani, Andhra Meal",800

In [288]:
# changing online_order into 1 and 0 ( for ml models)
data["Online_order"]

0       Yes
1       Yes
2       Yes
3        No
4        No
       ...
8245     No
8246     No
8247    Yes
8248     No
8249     No
Name: Online_order, Length: 8250, dtype: object

In [289]:
data["Online_order"] = data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0)

In [290]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 Out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 Out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 Out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 Out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 Out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 Out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 Out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 Out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 Out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 Out of 5,"Biryani, Andhra Meal",800

In [291]:
# saving clean data
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 Out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 Out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 Out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 Out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 Out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 Out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 Out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 Out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 Out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 Out of 5,"Biryani, Andhra Meal",800

In [292]:
data.to_csv("Cleaned_csv_file.csv")

In [295]:
pd.read_csv('Cleaned_csv_file.csv')

,Unnamed: 0,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,0,Jalsa,1,Yes,4.1 Out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,1,No,4.1 Out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,1,No,3.8 Out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,0,No,3.7 Out of 5,Masala Dosa,300
4,4,Grand Village,0,No,3.8 Out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
8245,8245,Chung Wah,0,No,2.5 Out of 5,Manchow Soup,800
8246,8246,Breakfast House,0,No,3.6 Out of 5,"Coffee, Vada, Mla Dosa",300
8247,8247,Fujian Express,1,No,3.8 Out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 Out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,8249,Bhagini,0,No,2.5 Out of 5,"Biryani, Andhra Meal",800

In [296]:
data.to_csv("Cleaned_csv_file_no_index.csv", index = False)

In [297]:
pd.read_csv("Cleaned_csv_file_no_index.csv")

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 Out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 Out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 Out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 Out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 Out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 Out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 Out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 Out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 Out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 Out of 5,"Biryani, Andhra Meal",800

In [298]:
data.to_excel("Cleaned_excel_file.xlsx")

In [300]:
data.to_excel('Cleaned_excel_file_no_index.xlsx',index=False)