In [69]:
import pandas as pd

In [70]:
data = pd.read_csv("onlinefoods.csv")

In [71]:
data.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes

In [72]:
data.shape

(388, 13)

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    object
 2   Marital Status              388 non-null    object
 3   Occupation                  388 non-null    object
 4   Monthly Income              388 non-null    object
 5   Educational Qualifications  388 non-null    object
 6   Family size                 388 non-null    int64
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64
 10  Output                      388 non-null    object
 11  Feedback                    388 non-null    object
 12  Unnamed: 12                 388 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 39.5+ KB

In [74]:
'''     Tasks: 
        1. Deleting redundant columns
        2. Renaming the columns
        3. Dropping duplicates
        4. Remove the NaN values from the dataset
        5. Check for some more Transformations
'''

'     Tasks: \n        1. Deleting redundant columns\n        2. Renaming the columns\n        3. Dropping duplicates\n        4. Remove the NaN values from the dataset\n        5. Check for some more Transformations\n'

# 1. Deleting redundant columns

In [75]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='object')

In [76]:
columns_to_keep = ['Age', 'Gender','Marital Status', 'Occupation', 'Monthly Income','Educational Qualifications', 'Family size','Feedback', 'Unnamed: 12']
columns_to_drop = ['latitude', 'longitude','Pin code','Unnamed: 12']

In [77]:
len(columns_to_keep)

9

In [78]:
len(columns_to_drop)

4

In [79]:
data.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes

## 1st method : Filtering the columns

In [80]:
modified_data  = data[columns_to_keep]

In [81]:
modified_data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Positive,Yes
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,Positive,Yes

## 2nd method : Dropping the unnecessary columns

In [82]:
data.drop(columns = columns_to_drop , inplace = True)

In [83]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Yes,Positive
384,23,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
385,22,Female,Single,Student,No Income,Post Graduate,5,Yes,Positive
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive
387,23,Male,Single,Student,No Income,Post Graduate,5,Yes,Positive

# 2. Renaming the columns

In [84]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'Output', 'Feedback'],
      dtype='object')

In [85]:
data.rename(columns = {'Monthly Income' : 'Monthly Salary'})

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,Yes,Positive
384,23,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
385,22,Female,Single,Student,No Income,Post Graduate,5,Yes,Positive
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive
387,23,Male,Single,Student,No Income,Post Graduate,5,Yes,Positive

# 3. Dropping duplicates

In [86]:
data.duplicated().value_counts()

False    244
True     144
Name: count, dtype: int64

In [87]:
data.drop_duplicates(inplace = True)

In [88]:
data.duplicated().value_counts()

False    244
Name: count, dtype: int64

# 4 . Remove the NaN values from the dataset

In [89]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
Output                        0
Feedback                      0
dtype: int64

In [90]:
# No NaN values in the dataset

# 5. Check for some more Transformations

In [91]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive
...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,No,Positive
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Yes,Positive
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Yes,Positive
374,21,Male,Single,Student,No Income,Graduate,3,Yes,Negative
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive

In [92]:
# changing the age ( years) to age ( months)
data['Age (Months)'] = data ['Age']*12

In [93]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Output,Feedback,Age (Months)
0,20,Female,Single,Student,No Income,Post Graduate,4,Yes,Positive,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive,288
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative,264
3,22,Female,Single,Student,No Income,Graduate,6,Yes,Positive,264
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive,264
...,...,...,...,...,...,...,...,...,...,...
355,21,Male,Single,Student,No Income,Graduate,2,No,Positive,252
363,31,Male,Married,Employee,More than 50000,Ph.D,3,Yes,Positive,372
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Yes,Positive,360
374,21,Male,Single,Student,No Income,Graduate,3,Yes,Negative,252
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Yes,Positive,276

In [94]:
# changing the gender female to F and male to M

In [95]:
data['Gender'] = data['Gender'].apply(lambda x:'F' if x == 'Female' else 'M')

In [96]:
data['Gender']

0      F
1      F
2      M
3      F
4      M
      ..
355    M
363    M
369    M
374    M
386    M
Name: Gender, Length: 244, dtype: object

In [97]:
data.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Output,Feedback,Age (Months)
0,20,F,Single,Student,No Income,Post Graduate,4,Yes,Positive,240
1,24,F,Single,Student,Below Rs.10000,Graduate,3,Yes,Positive,288
2,22,M,Single,Student,Below Rs.10000,Post Graduate,3,Yes,Negative,264
3,22,F,Single,Student,No Income,Graduate,6,Yes,Positive,264
4,22,M,Single,Student,Below Rs.10000,Post Graduate,4,Yes,Positive,264

In [98]:
# If family size > 3 its going to be large else small

In [99]:
data['Family size'] = data['Family size'].apply(lambda x: 'Large' if x>3 else 'Small')

In [100]:
data['Family size']

0      Large
1      Small
2      Small
3      Large
4      Large
       ...
355    Small
363    Small
369    Large
374    Small
386    Small
Name: Family size, Length: 244, dtype: object

In [101]:
# changing output values 'yes' - 1 and 'no' - 0

In [102]:
data['Output'] = data['Output'].apply(lambda x: 1 if x=='Yes' else 0 )

In [103]:
data['Output']

0      1
1      1
2      1
3      1
4      1
      ..
355    0
363    1
369    1
374    1
386    1
Name: Output, Length: 244, dtype: int64

# Exporting the cleaned data into csv and excel files

In [106]:
data.to_csv("Cleaned_data_csv.csv")

In [107]:
data.to_excel("Cleaned_data_excel.xlsx")