In [231]:
import pandas as pd

In [232]:
data = pd.read_csv("HR-Employee-Attrition.csv")

In [233]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [234]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [235]:
'''     Tasks: 
        1. Deleting redundant columns
        2. Renaming the columns
        3. Dropping duplicates
        4. Cleaning individual columns
        5. Remove the NaN values from the dataset
        6. Check for some more Transformations
'''

'     Tasks: \n        1. Deleting redundant columns\n        2. Renaming the columns\n        3. Dropping duplicates\n        4. Cleaning individual columns\n        5. Remove the NaN values from the dataset\n        6. Check for some more Transformations\n'

# 1. Deleting redundant columns

In [236]:
data.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [237]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [238]:
data.head(3).iloc[:,13:22]

,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18
0,3,2,Sales Executive,4,Single,5993,19479,8,Y
1,2,2,Research Scientist,2,Married,5130,24907,1,Y
2,2,1,Laboratory Technician,3,Single,2090,2396,6,Y

In [239]:
columns_to_keep=['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department','DistanceFromHome', 'Education','HourlyRate','JobRole','YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion','YearsWithCurrManager']
columns_to_drop=['EducationField', 'EmployeeCount','EmployeeNumber', 'EnvironmentSatisfaction', 'Gender','JobInvolvement', 'JobLevel','JobSatisfaction','MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked','Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating','RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel','TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',]

In [240]:
len(columns_to_drop)

22

In [241]:
len(columns_to_keep)

13

In [242]:
data.shape

(1470, 35)

## 1st method

In [243]:
new_data = data[columns_to_keep]

In [244]:
new_data.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7

## 2nd method

In [245]:
data_new_2 = data.drop(columns=columns_to_drop)

 ### -----

In [246]:
data.drop(columns=columns_to_drop,inplace = True)

In [247]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

# 2. Renaming the columns

In [248]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [249]:
data.rename(columns = {'DistanceFromHome':'DistanceHome'},inplace = True)

In [250]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceHome', 'Education', 'HourlyRate', 'JobRole', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [251]:
data.rename(columns = {'DailyRate':'DailyWage' , 'HourlyRate':'HourlyWage'},inplace =True)

In [252]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyWage', 'Department',
       'DistanceHome', 'Education', 'HourlyWage', 'JobRole', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

# 3. Dropping duplicates

In [253]:
data.duplicated().sum()

np.int64(0)

In [254]:
data.duplicated().value_counts()

False    1470
Name: count, dtype: int64

In [255]:
# NO duplicated values

# 4. Cleaning Individual columns

In [256]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [257]:
data.shape

(1470, 13)

In [258]:
# if we are looking for the people ,who is in the company < 8 years

In [259]:
data[data["YearsAtCompany"] <= 8].shape

(1022, 13)

In [260]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [261]:
data.shape

(1470, 13)

In [262]:
data[data["Attrition"] == 'Yes' ]["Attrition"].unique()
# o/p indicates that the column only has 'yes'

array(['Yes'], dtype=object)

In [263]:
data["BusinessTravel"].str.replace("_"," ")

0           Travel Rarely
1       Travel Frequently
2           Travel Rarely
3       Travel Frequently
4           Travel Rarely
              ...
1465    Travel Frequently
1466        Travel Rarely
1467        Travel Rarely
1468    Travel Frequently
1469        Travel Rarely
Name: BusinessTravel, Length: 1470, dtype: object

In [264]:
data["BusinessTravel"][1]

'Travel_Frequently'

In [265]:
data["Attrition"].unique()

array(['Yes', 'No'], dtype=object)

In [274]:
data['BusinessTravel'] = data["BusinessTravel"].str.replace("_"," ")

In [275]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

# 5. Removing the NaN Values from the dataset

In [271]:
data.isna().sum()

Age                        0
Attrition                  0
BusinessTravel             0
DailyWage                  0
Department                 0
DistanceHome               0
Education                  0
HourlyWage                 0
JobRole                    0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [ ]:
# no NaN values in the dataset

# 6. Check for some more Transformations

In [ ]:
# changing the attrition values , yes: 1 and no : 0

In [273]:
data.head(3)

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0

In [277]:
data["Attrition"] = data["Attrition"].apply(lambda x : 1 if x=='Yes' else 0 )

In [278]:
data["Attrition"]

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int64

In [279]:
type(data["Attrition"][1])

numpy.int64

# Exporting the cleaned data

In [280]:
data.to_csv("Cleaned_data_csv.csv")

In [281]:
data.to_excel("Cleaned_data_excel.xlsx")