In [53]:
import pandas as pd

In [54]:
pd.__version__

'2.3.3'

In [55]:
data = pd.read_csv('Expanded_data_with_more_features.csv')

In [56]:
data.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           30641 non-null  int64
 1   Gender               30641 non-null  object
 2   EthnicGroup          28801 non-null  object
 3   ParentEduc           28796 non-null  object
 4   LunchType            30641 non-null  object
 5   TestPrep             28811 non-null  object
 6   ParentMaritalStatus  29451 non-null  object
 7   PracticeSport        30010 non-null  object
 8   IsFirstChild         29737 non-null  object
 9   NrSiblings           29069 non-null  float64
 10  TransportMeans       27507 non-null  object
 11  WklyStudyHours       29686 non-null  object
 12  MathScore            30641 non-null  int64
 13  ReadingScore         30641 non-null  int64
 14  WritingScore         30641 non-null  int64
dtypes: float64(1), int64(4), object(10)
memory usage: 3.5+ MB

In [58]:
'''     Tasks: 
        1. Deleting redundant columns
        2. Renaming the columns
        3. Dropping duplicates
        4. Remove the NaN values from the dataset
        5. Check for some more Transformations
'''

'     Tasks: \n        1. Deleting redundant columns\n        2. Renaming the columns\n        3. Dropping duplicates\n        4. Remove the NaN values from the dataset\n        5. Check for some more Transformations\n'

# 1. Deleting redundant columns

In [59]:
data.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild',
       'NrSiblings', 'TransportMeans', 'WklyStudyHours', 'MathScore',
       'ReadingScore', 'WritingScore'],
      dtype='object')

In [60]:
columns_to_drop =['Unnamed: 0','TestPrep', 'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild',]

In [61]:
data.drop(columns = columns_to_drop ,inplace = True)

In [62]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

# 2. Renaming the columns

In [63]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [64]:
# changing name 'NrSiblings' to 'NumberofSiblings'

In [65]:
data.rename(columns = {'NrSiblings':'NumberofSiblings'},inplace=True)

In [66]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,NaN,bachelor's degree,standard,3.0,school_bus,< 5,71,71,74
1,female,group C,some college,standard,0.0,NaN,5 - 10,69,90,88
2,female,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,1.0,NaN,5 - 10,45,56,42
4,male,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...
30636,female,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,male,group E,high school,standard,1.0,private,5 - 10,58,53,51
30638,female,NaN,high school,free/reduced,1.0,private,5 - 10,61,70,67
30639,female,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93
30640,male,group B,some college,standard,1.0,school_bus,5 - 10,64,60,58

# 3. Dropping duplicates

In [67]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
30636    False
30637    False
30638    False
30639    False
30640     True
Length: 30641, dtype: bool

In [68]:
data.duplicated().value_counts()

False    30632
True         9
Name: count, dtype: int64

In [69]:
data.drop_duplicates(inplace = True)

In [70]:
data.duplicated().value_counts()

False    30632
Name: count, dtype: int64

# 4. Remove the NaN values from the dataset

In [71]:
data.isna().sum()

Gender                 0
EthnicGroup         1840
ParentEduc          1845
LunchType              0
NumberofSiblings    1571
TransportMeans      3134
WklyStudyHours       955
MathScore              0
ReadingScore           0
WritingScore           0
dtype: int64

In [72]:
data.dropna(inplace = True)

In [73]:
data.isna().sum()

Gender              0
EthnicGroup         0
ParentEduc          0
LunchType           0
NumberofSiblings    0
TransportMeans      0
WklyStudyHours      0
MathScore           0
ReadingScore        0
WritingScore        0
dtype: int64

#  5. Check for some more Transformations

In [74]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
2,female,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
4,male,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
5,female,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
6,female,group B,some college,standard,1.0,private,5 - 10,85,93,89
7,male,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...
30634,male,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
30635,male,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
30636,female,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,male,group E,high school,standard,1.0,private,5 - 10,58,53,51
30639,female,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [76]:
data['Gender'] = data['Gender'].apply(lambda x: 'F' if x == 'Female' else 'M')

In [77]:
data['Gender']

2        M
4        M
5        M
6        M
7        M
        ..
30634    M
30635    M
30636    M
30637    M
30639    M
Name: Gender, Length: 22343, dtype: object

In [79]:
data.reset_index(inplace = True)

In [80]:
data

,index,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,2,M,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
1,4,M,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
2,5,M,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
3,6,M,group B,some college,standard,1.0,private,5 - 10,85,93,89
4,7,M,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...,...
22338,30634,M,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
22339,30635,M,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
22340,30636,M,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
22341,30637,M,group E,high school,standard,1.0,private,5 - 10,58,53,51
22342,30639,M,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [82]:
data.drop(columns = ['index'] ,inplace=True)

In [83]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,M,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
1,M,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
2,M,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
3,M,group B,some college,standard,1.0,private,5 - 10,85,93,89
4,M,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...
22338,M,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
22339,M,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
22340,M,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
22341,M,group E,high school,standard,1.0,private,5 - 10,58,53,51
22342,M,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [85]:
data['NumberofSiblings'] = data['NumberofSiblings'].astype('int')

In [86]:
data['NumberofSiblings']

0        4
1        0
2        1
3        1
4        1
        ..
22338    2
22339    2
22340    2
22341    1
22342    3
Name: NumberofSiblings, Length: 22343, dtype: int64

In [87]:
# Extracting cleaned data into csv and excel file

In [88]:
data.to_csv('Cleaned_data_csv.csv')

In [89]:
data.to_excel('Cleaned_data_excel.xlsx')