In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("amazon_product.csv")

In [3]:
data.head(5)

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [4]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     object
 2   product_title                64 non-null     object
 3   product_price                64 non-null     object
 4   product_original_price       27 non-null     object
 5   currency                     64 non-null     object
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_url                  64 non-null     object
 9   product_photo                64 non-null     object
 10  product_num_offers           64 non-null     int64
 11  product_minimum_offer_price  64 non-null     object
 12  is_best_seller               64 non-null     bool
 13  is_amazon_choice             64 non-null     bool
 14  is_prime                     64 non-null     bool
 15  climate_pledge_friendly      64 non-null     bool
 16  sales_volume                 61 non-null     object
 17  delivery                     63 non-null     object
 18  has_variations               64 non-null     bool
 19  product_availability         1 non-null      object
 20  unit_price                   5 non-null      object
 21  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), object(12)
memory usage: 8.9+ KB

In [6]:
'''     Tasks: 
        1. Deleting redundant columns
        2. Renaming the columns
        3. Dropping duplicates
        4. Remove the NaN values from the dataset
        5. Check for some more Transformations
'''

'     Tasks: \n        1. Deleting redundant columns\n        2. Renaming the columns\n        3. Dropping duplicates\n        4. Remove the NaN values from the dataset\n        5. Check for some more Transformations\n'

# 1. Deleting redundant columns

In [7]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [8]:
columns_to_drop = ['Unnamed: 0', 'asin','product_url', 'product_photo','product_num_offers','product_minimum_offer_price','is_amazon_choice','is_prime', 'climate_pledge_friendly','sales_volume', 'delivery', 'has_variations', ]

In [9]:
data.drop(columns = columns_to_drop,inplace = True)

In [10]:
data.head(5)

,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,is_best_seller,product_availability,unit_price,unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,False,NaN,NaN,NaN

# 2. Renaming the columns

In [11]:
data.head(4)

,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,is_best_seller,product_availability,unit_price,unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN

In [12]:
data_new_columns=[]
for col in data.columns:
    data_new_columns.append(col.capitalize())

In [13]:
data.columns = data_new_columns

In [14]:
data.columns

Index(['Product_title', 'Product_price', 'Product_original_price', 'Currency',
       'Product_star_rating', 'Product_num_ratings', 'Is_best_seller',
       'Product_availability', 'Unit_price', 'Unit_count'],
      dtype='object')

# 3. Dropping duplicates

In [15]:
data.duplicated().value_counts()

False    64
Name: count, dtype: int64

In [16]:
data.duplicated().sum()

np.int64(0)

In [17]:
# there are no duplicates in the data

# 4. Remove the NaN values from the dataset

In [28]:
data.isna().sum()

Product_title              0
Product_price              0
Product_original_price    37
Currency                   0
Product_star_rating       10
Product_num_ratings        0
Is_best_seller             0
Product_availability      63
Unit_price                59
Unit_count                59
dtype: int64

In [29]:
data.dropna(inplace = True)

In [30]:
data.isna().sum()

Product_title             0
Product_price             0
Product_original_price    0
Currency                  0
Product_star_rating       0
Product_num_ratings       0
Is_best_seller            0
Product_availability      0
Unit_price                0
Unit_count                0
dtype: int64

#  5. Check for some more Transformations

In [18]:
data.head(5)

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,False,NaN,NaN,NaN

In [19]:
data["Is_best_seller"] = data["Is_best_seller"].apply(lambda x: 1 if x == True else 0)

In [20]:
data["Is_best_seller"]

0     0
1     0
2     0
3     0
4     0
     ..
59    0
60    1
61    0
62    1
63    1
Name: Is_best_seller, Length: 64, dtype: int64

In [21]:
data["Product_price"] = data["Product_price"].str.replace("$","")

In [22]:
data["Product_price"].astype(float)

0      99.99
1     149.74
2      49.88
3     335.00
4     199.99
       ...
59     34.98
60     14.99
61      0.00
62     69.99
63     59.99
Name: Product_price, Length: 64, dtype: float64

In [23]:
data["Product_price"] = data["Product_price"].astype(float)

In [24]:
data

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,$169.99,USD,4.0,2929,0,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,$158.00,USD,4.2,135,0,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,NaN,USD,3.9,205,0,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,$499.00,USD,4.3,2248,0,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,NaN,USD,4.1,423,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,34.98,NaN,USD,NaN,0,0,NaN,NaN,NaN
60,Swan Song,14.99,$30.00,USD,4.4,14471,1,NaN,NaN,NaN
61,Bluey: Let&#x27;s Play!,0.00,NaN,USD,3.5,270,0,NaN,NaN,NaN
62,Xbox Wireless Controller – Sky Cipher Special ...,69.99,NaN,USD,2.6,12,1,NaN,NaN,NaN
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,$84.99,USD,4.0,48154,1,NaN,NaN,NaN

In [25]:
type(data["Product_price"][0])

numpy.float64

In [26]:
data["Product_price"] = data['Product_price'].apply(lambda x: round(x))

In [27]:
data["Product_price"]

0     100
1     150
2      50
3     335
4     200
     ...
59     35
60     15
61      0
62     70
63     60
Name: Product_price, Length: 64, dtype: int64

# Exporting the cleaned data

In [31]:
data.to_csv("Cleaned_data_csv.csv")

In [32]:
data.to_excel("Cleaned_data_excel.xlsx")